[tool.poetry]
name = "radio_recoder"
version = "0.1.0"
description = ""
authors = ["Ryu Yamada"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"
m3u8 = "^0.5.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
